(* Copyright 2024 Emilio Jesús Gallego Arias *)
(*  *)
(* Use of this source code is governed by an MIT-style *)
(* license that can be found in the LICENSE file or at *)
(* https://opensource.org/licenses/MIT. *)
